name: Remote update execution
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 35.228.87.203
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
            cd /home/health_checks/cmg_health_checks
            git config --global --add safe.directory /home/health_checks/cmg_health_checks
            git checkout master
            git pull origin master --allow-unrelated-histories