name: ci

on:
    push:
    pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
          - "3.10"

    name: Test
    runs-on: ${{ matrix.os}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          git clone https://github.com/wagesreiterb/lazySSH/
          pip install -r ./lazySSH/requirements.txt
          python ./lazySSH/main.py &

      - name: Test with unittest
        run: |
          cd cmg_health_checks
          python -m unittest -v unittests.TestCmgQuery
